CREATE TABLE post_countdown_content (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title TEXT,
    subtitle TEXT,
    hero_video_url TEXT,
    hero_video_description TEXT,
    cta1_text TEXT,
    cta1_link TEXT,
    cta2_text TEXT,
    cta2_link TEXT,
    cta3_text TEXT,
    cta3_link TEXT,
    roadmap_title TEXT,
    roadmap_subtitle TEXT,
    video_story_title TEXT,
    video_story_subtitle TEXT,
    join_movement_title TEXT,
    join_movement_cta1_text TEXT,
    join_movement_cta1_link TEXT,
    join_movement_cta2_text TEXT,
    join_movement_cta2_link TEXT,
    join_movement_cta3_text TEXT,
    join_movement_cta3_link TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO post_countdown_content (title, subtitle, hero_video_url, hero_video_description, cta1_text, cta1_link, cta2_text, cta2_link, cta3_text, cta3_link, roadmap_title, roadmap_subtitle, video_story_title, video_story_subtitle, join_movement_title, join_movement_cta1_text, join_movement_cta1_link, join_movement_cta2_text, join_movement_cta2_link, join_movement_cta3_text, join_movement_cta3_link) VALUES (
    'MittiMitra™',
    'Real-Time Soil Customizer for Every Indian Farm',
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'अब मिट्टी बताएगी, क्या चाहिए फ़सल को।',
    'Join the Waitlist',
    '/#',
    'See What''s Coming Next',
    '/our-story',
    'Share Your Thoughts',
    'mailto:info@electroculture.in',
    'MittiMitra is just the beginning.',
    'Follow our journey from analog sensors to fully autonomous farming',
    'Follow Our Journey — From Sketch to Soil',
    'Behind-the-scenes videos showing our development process',
    'We''re building in public. And we want you in this story.',
    'Join Our Team',
    '/careers',
    'Notify Me When MittiMitra Launches',
    '/#',
    'Share Your Suggestion',
    'mailto:info@electroculture.in'
);
